version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    volumes:
      - redis:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - .env
    volumes:
      - meilisearch:/data.ms

  slanger-backend:
    build: ./
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - meilisearch

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx:/etc/nginx

volumes:
  postgres:
  redis:
  meilisearch:
  nginx:
