version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
      # - $PWD/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    # volumes:
      # - $PWD/redis:/var/lib/redis/data

  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - .env
    ports:
      - 7700:7700
    # volumes:
      # - $PWD/meilisearch:/var/lib/meilisearch/data

  slanger-backend:
    build: ./
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - meilisearch
    ports:
      - 3000:3000

# volumes:
  # postgres:
  # redis:
  # meilisearch:
